### PR TITLE
fix: logic for multiple tracker with same key (fixes #47)

### LINKED ISSUE #47: MaxValueTracker returns stale cache entries and overwrites higher values
If multiple `MaxValueTracker`s are instantiated for the same key, the tracker will not work as expected. I added some [test cases](https://github.com/interledgerjs/ilp-plugin-payment-channel-framework/blob/da-maxValueTracker/test/backendSpec.js#L100-L121) to demonstrate the problem. [Here](https://circleci.com/gh/interledgerjs/ilp-plugin-payment-channel-framework/166?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is the result of running the test caess.

cc @sharafian

### PR DESCRIPTION
**Pull request by dappelt**

### CODE REVIEW

File: src/util/backend.js [hunk 1]
```diff
@@ -284,34 +279,39 @@ class MaxValueTracker {
...
-
-      return last
-    }
-
-    return entry
+    // By wrapping .getMax() and .put() in a Promise and queue it
+    // into writeQueue we ensure that consecutive calls to setIfMax do not
+    // interrupt a previous call
+    let readWritePromise
+    writeQueue = writeQueue.then(() => {
```
Comment (sharafian) [inline src/util/backend.js:284]: this callback can be an async function so you can use await inside of it

**Review by sharafian — APPROVED** [review]
LGTM except small change

File: src/util/backend.js (hunk 1 above)
Comment (dappelt) [reply src/util/backend.js:284]: Changed the callback in the next line to use async / await
