### PR TITLE
fix: decode username and password

### LINKED ISSUE #40: decode username and password from connection string
Username and password provided in the connection string are not decoded. For example, providing a client plugin with the option `server: btp+ws://username with blanks:shh its a secret@some.example:3333` will result in user and pass being parsed as `username%20with%20blank` and `shh%20its%20a%secret`, respectively.

### PR DESCRIPTION
**Pull request by dappelt**
fixes #40

### CODE REVIEW

**Review by michielbdejong — APPROVED** [review]

File: test/clientSpec.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ const info = {
 
 const peerAddress = 'example.red.server'
 const options = {
-  server: 'btp+wss://user:placeholder@example.com/rpc'
+  server: 'btp+wss://user:shhh secret@example.com/rpc'
```
Comment (michielbdejong) [inline test/clientSpec.js:36]: actually, since this is a URI, I think this should be `shhh%20secret`, then?

Comment (dappelt) [reply test/clientSpec.js:36]: When passing the connection string to the [URL constructor](https://github.com/interledgerjs/ilp-plugin-payment-channel-framework/blob/9cf6c18f10a803f4dfef3629498113f361f03771/src/lib/client.js#L18) the string is encoded. So this string here should not be url-encoded. Otherwise, it would get encoded twice.

Comment (michielbdejong) [reply test/clientSpec.js:36]: what if the username contains a `:` or the password contains a `@`?

Comment (dappelt) [reply test/clientSpec.js:36]: It cannot. I guess that's the downside of cramming the credentials into the URL. Wasn't there the option to define username and password as separate properties? (cc @sharafian )

Comment (sharafian) [reply test/clientSpec.js:36]: There was originally an option to specify credentials separately but it was removed in favor of a single BTP URI format
